name: UpgradeForge
version: '1.0.0'
main: io.github.febriez.upgradeForge.UpgradeForgeMain
api-version: '1.21'
authors: [ CoffeeTory ]
description: 강화 기능
website: "Discord: coffeetory"

commands:
  강화:
    description: 강화 명령어